### ISSUE TITLE
Links do not work in production

### ISSUE THREAD

**Issue by cdesch** [FlyoverWorks/storytime#91] opened 2015-02-19 14:47 UTC
In production, when selecting the Media, Snippets and Users menu Items it directs to my local server IP address. 

    http://192.168.1.112:8080/blog/storytime/media
    http://192.168.1.112:8080/blog/storytime/snippets
    http://192.168.1.112:8080/blog/storytime/users

The other links work fine by using the domain instead of the IP. 

    http://mydomain.com/blog/storytime/posts?type=blog_post
    http://mydomain.com/blog
    http://mydomain.com/blog/storytime/posts?type=page
    http://mydomain.com/blog/storytime/sites/1/edit

This also prevents Media Uploads to S3 when editing a draft of a blog post.

**Comment by bcroesch** [comment] 2015-02-19 14:57
Thanks @cdesch 

@dvanderbeek and @eanlain - we should use the _path version of the helpers that print those urls rather than _url (or the only_path option for anything using url_for). Either of you have time to make that switch today?

**Comment by eanlain** [comment] 2015-02-19 15:15
@cdesch I'm not able to reproduce this on any of the production sites we're using Storytime on. 

Is there somewhere in your app that you're specifying your local domain (192.168.1.112:8080), i.e. `config/environments/production.rb`?

**Comment by cdesch** [comment] 2015-02-19 15:44
No. Nothing in the `production.rb`

I did discover I'm running storytime version 1.07. Let me upgrade to 1.2 and deploy to production and see if it still occurs.

**Comment by cdesch** [comment] 2015-02-23 15:38
Bumping storytime to 1.2 did not fix the issue.

**Comment by bcroesch** [comment] 2015-02-23 15:38
Thanks for the heads up. We'll change those url helpers to use the path version to see if that helps. Will give you a heads up when that's pushed out.

**Comment by bcroesch** [comment] 2015-02-23 23:31
@cdesch - can you try switching to run off of master and see if that fixes the issue? I just pushed a commit to it that I think may work. If it does, we can push a 1.2.1 release.

```
gem 'storytime', github: 'flyoverworks/storytime', branch: 'master'
```

**Comment by cdesch** [comment] 2015-02-24 00:53
That seems to have corrected the error. 

on a different note, there is a new tab `Subscriptions` which throws an "you are not authorized to perform this action." Was there a migration step I missed in updating the gem?

**Comment by bcroesch** [comment] 2015-02-24 01:22
Just pushed a fix on master. It should have been wrapped in a check to the pundit policy to ensure the user has the permission to manage subscriptions.

**Comment by dvanderbeek** [comment] 2015-02-24 01:31
You might be missing the actual permission records in the database. I'll have to look later to see if the migrations are missing some code to add the new data



—

**Comment by bcroesch** [comment] 2015-02-24 01:34
I looked at the migration that creates subscriptions, and it calls Action.seed and Permission.seed, so hopefully it should be in there.

@cdesch - if the current master doesn't fix that issue, try running 
```
Storytime::Action.seed
Storytime::Permission.seed
```
in a console.

**Comment by bcroesch** [comment] 2015-02-24 04:05
Going to close this since the original issue is fixed. If need be, we can open another for the subscriptions issue.

**Closed by bcroesch** 2015-02-24 04:05 UTC

**Comment by cdesch** [comment] 2015-02-24 14:42
Doing a 

    bundle exec rake storytime:install:migrations
 
and 

     bundle exec rake db:migrate

Fixed it. I guess storytime doesn't check to make sure the most recent required migrations have taken place.

**Comment by bcroesch** [comment] 2015-02-25 14:33
I'm not aware of a way to have the engine check if its migrations have been copied/run, the way a host app checks for pending migrations.

That said, we should do a little better job of indicating when there is a need to install new migrations (version upgrades, for instance). When Storytime 2.0 is released in the next week or two, we'll plan to write up an upgrade guide (though I expect it to be fairly simple/short).

**Comment by cdesch** [comment] 2015-02-25 15:08
An upgrade guide would be great. A summary change log would be nice for any notable differences between the minor versions.
